version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin#123
      MYSQL_DATABASE: fastSelectionDatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha-rede

  app:
    build: .
    container_name: backend-aspnet
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=fastSelectionDatabase;User=root;Password=Admin#123;Persist Security Info=False;
    networks:
      - minha-rede

networks:
  minha-rede:

volumes:
  mysql_data: